import Head from "next/head";
import Firstpart from "../components/firstpart";
import Link from "next/link";

export default function Home() {
  return (
    <div className="w-full bg-red-200 h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" flex  items-center w-full text-center">
        <h1 className="bg-gray-500 w-full  p-12   text-xl text-zinc-200 ">
          Probando Next js
        </h1>
      </div>
      <div className="flex justify-evenly mt-8">  
      <div className="  border-4 w-20  bg-white" >
        <Link  href="/backOne">serverSide</Link>
      </div>
      <div className=" border-4 w-20  bg-white">
        <Link href="/htmlStatic">htmlStatic</Link>
      </div>
      <div className=" border-4 w-20  bg-white">
        <Link href="/sideClient">sideClient</Link>
      </div>
      </div>
      <h2 className="w-full bg-red-600 my-4 px-4 text-zinc-200 text-3xl">Rutas dinamicas</h2>
      <Firstpart />
    </div>
  );
}
